---
title: "통계 대중화를 위한 오픈통계 패키지 개발"
subtitle: "설치형 오픈 통계 패키지 - `Rcmdr`"
author: "이광춘 대표 / 에이아이에스"
institute: "에이아이에스"
date: "2022-05-11"
output:
  xaringan::moon_reader:
    css: 
      - [default]
      - css/bitstat.css
      - css/nhsr-fonts.css
    lib_dir: libs
    seal: false
    nature:
      highlightStyle: googlecode
      highlightLines: true
      highlightLanguage: ["r"]
      countIncrementalSlides: false
      ratio: "4:3"
      beforeInit: "macros.js"
    includes:
      after_body: [css/insert-logo-bitstat.html]
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
library(tidyverse)
# library(nhsrtheme)
# library(NHSRdatasets)
# set default options

options(
  htmltools.dir.version = FALSE, 
  htmltools.preserve.raw = FALSE,
  tibble.width = 60, tibble.print_min = 6,
  crayon.enabled = TRUE
)

knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE,
                      comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center',
                      fig.width = 7.252,
                      fig.height = 4,
                      dpi = 300)

# uncomment the following lines if you want to use the NHS-R theme colours by default
# scale_fill_continuous <- partial(scale_fill_nhs, discrete = FALSE)
# scale_fill_discrete <- partial(scale_fill_nhs, discrete = TRUE)
# scale_colour_continuous <- partial(scale_colour_nhs, discrete = FALSE)
# scale_colour_discrete <- partial(scale_colour_nhs, discrete = TRUE)
```


class: title-slide, left, bottom

# `r rmarkdown::metadata$title`
----
## **`r rmarkdown::metadata$subtitle`**
### `r rmarkdown::metadata$author`
### `r rmarkdown::metadata$date`

 
---
class: inverse, middle
name: data-science-case

# 발표 개요 

----

.pull-left[

디지털 전환이 급속도로 진행됨에 따라 **.warmyellow[디지털 스킬셋 양극화]** 심화되고 있지만,
코딩중심 소프트웨어 중심 인프라 및 교육에 편중되어 
누구나 쉽게 사용할 수 있는 한글 오픈 통계 패키지 보급 필요.

논문과 데이터 분석 통계작업용 **.green[외산 상용 통계 패키지 국산화]**는 물론,
**.green[통계 대중화]**를 위한 통계 콘텐츠 개발 및 공개하고 통계커뮤니티 연계하여
오픈 소스 소프트웨어 기여.

]
 
.pull-right[   
.left[

1\. [마무리](#bitstat-goodbye) 

]
] <!--end of right-column-->  
  
<!--------------------------  1. 개발 필요성 ----------------------------------------->
 
 
```{r child='slideshows/daejeon/daejeon-goodbye.Rmd'}
```










