---
layout: page
title: "데이터과학 방법론 산업적용 현재와 미래"
subtitle: "<small>국가통계방법론 심포지엄: 국가통계의 현재와 미래</small>"
author: "<br> <br> <br> <small>삼정 KPMG <br> 이광춘</small>"
date: "2020-09-24"
output:
  revealjs::revealjs_presentation:
    includes:
       in_header: GA_script.html
    css: styles/mlflow.css
    df_print: paged
    self_contained: false
    center: true
    fig_width: 6
    fig_height: 4
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
options(htmltools.dir.version = FALSE)

knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE,
                    comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')

```

# 

```{r stat-symposium}
library(tidyverse)
library(magick)
library(slickR)

poster <- image_read("fig/stat_symposium.jpg")

poster_01 <- poster %>% 
  image_crop(geometry = geometry_area(750, 970,0, 0))

poster_02 <- poster %>% 
  image_crop(geometry = geometry_area(750, 1050, 0, 970))

poster_03 <- poster %>% 
  image_crop(geometry = geometry_area(750, 1170, 0, 970 + 1075))

poster_01 %>% 
  image_write("fig/poster_01.png")

poster_02 %>% 
  image_write("fig/poster_02.png")

poster_03 %>% 
  image_write("fig/poster_03.png")

fig_files <- list.files("fig")

poster_filenames <- fig_files[str_detect(fig_files, "poster_.*")]

poster_df <- tibble(page = glue::glue("fig/{poster_filenames}") )
  
slickR(poster_df$page, height = 500)

```


# 관련 자료

## 시작



