---
title: "기계의 역습 - 설명가능한 기계학습"
subtitle: "Explainable Machine Learning"
author: "이광춘 <br/> (<a href='https://software-carpentry.org/'> 소프트웨어 카펜트리 </a>)"
date: "2018/11/08"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ["default"]
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)

knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE,
                    comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')

```

class: inverse, middle, center

# 비즈니스 기회창출

---
## 기업의 기계학습 알고리즘 활용

- 반복적 업무나 중요한 의사결정을 내리는데 기계학습 알고리즘을 활용하여 **거래비용**을 줄이고, **정보유통**을 활발히 하며, 양질의 **제품/서비스 정보**를 고객에게 제공.
    - **다이내믹프라이싱(DynamicPricing)**: 가격민감도가 서로 다른 고객들에게 차별화된 가격을 제시. 이를 통해 알고리즘 기반으로 실시간 가격차별화를 통해 ~~단일가격을 책정~~했을때 대비하여  더 큰이익을 창출
    - 알고리즘 활용 추천시스템: 사용자 행동패턴, 사용자간 관계, 상품유사도를 바탕으로 고객의 취향과 선호를 예측, 이에 적합한 상품을 추천하여 마케팅 효과를 높임.
    - 금융업계 알고리즘 활용 사례: 알고리즘트레이딩, 로보어드바이저, 신용평가시스템


.footnote[이효정, 최성집 (June 2018), "비즈니스 기회창출을 위한 AI알고리즘의 활용", 삼정KPMG 경제연구원, ISSUE MONITOR, 제84호]

---
class: inverse, middle, center

# 기계학습 알고리즘을 통한 비즈니스 기회창출 관련 주요 이슈와 쟁점

---
## 기계학습 알고리즘 이슈와 쟁점

- **알고리즘 담합**: 경쟁사업자들이 알고리즘을 이용하여 가격, 공급량 등을 조정하거나 관련 정보를 공유하는 행태를 의미. 알고리즘 담합은 시장 경쟁강도를 약화시키고 산업의 혁신을 저하시킴.
- **EU GDPR(개인정보보호규정)도입과 알고리즘 규제** : GDPR 에는 알고리즘이 내리는 자동화된 의사결정에 대해 설명을 요구할 수 있는 권리가 포함되어 있음. 따라서, GDPR도입에 따라 **예측은 뛰어나지만 설명이 어려운** 실무에서 많이 사용되는 블랙박스 예측 및 추천 알고리즘에 대한 완전한 점검이 필요하다는 논의가 제기되고 있음
- **윤리적 알고리즘** : 알고리즘 설계시 **인간의 개입에 따른 오류와 편향성**의 발생가능성이 존재하므로, 각국정부와 기업, 학계는 알고리즘의 활용이 윤리적 방향성을 지녀야 한다는 데 공감이 확산되고 있음.


