---
title: "디지털 뉴딜"
subtitle: "디지털 뉴딜와 지역균형 발전"
description: |
  코로나19로 인한 전대미문의 경제위기와 미중 무역갈등으로 수출에 크게 의존하고 있는 한국경제는 큰 전환점을 맞이하고 있다. 특히, 급격한 가계부채 증가와 코로나19 대응을 위한 확대 재정정책으로 정부 재정 건정성도 이슈로 부각되고 있다. 이런 와중에 코로나19로 비대면 생활이 자리를 잡으면서 디지털 격차 확대와 인공지능(AI) 부상으로 자동화 추세에 속도가 붙고 있다. 
  이러한 엄중한 경제적 위기와 사회변혁 상황에서 인공지능으로 대표되는 디지털 전환(Digital Transformation) 시기에 선제적으로 대응하기 위하여 2020년 7월 **한국판 뉴딜**이라는 명칭으로 2025년까지 160조를 투자하여 일자리 190만개를 창출하는 초대형 추진계획을 발표하였다. 디지털 뉴딜과 그린 뉴딜을 성장의 양대축으로 삼고 심화되는 불평등을 안전망 강화를 통해 사회적 안전판을 삼는 것을 주요 골자로 하고 있다. 
  과거 국가의 경쟁력을 단순히 인구와 국내총생산만을 주로 평가하던 것에서 더 나아가 인간개발지수(HDI), 부패인식지수(CPI), 경제자유지수(IEF), 민주화 지수, 세계평화지수(GPI) 등이 추가된 것이 얼마되지 않았다. 제4차 산업혁명으로 디지털 전환(Digital Transformation)이 부상하면서 다시 OECD 국가를 디지털 전환이 빠른 국가와 느린 국가로 나누고 있으며 이제는 AI 준비성(AI Readiness)과 디지털 경쟁력(Digital Competitiveness)이 미래 선진국가로 자리매김하는 중요지표로 평가하고 있다.
  본고에서는 코로나19와 미중 무역전쟁으로 심화된 불활실성을 선제적으로 대응하고자 정부에서 제시한 **디지털 뉴딜**에 대하여 디지털 경쟁력, 데이터 경제, AI 준비성을 중심으로 2020년 10월 12일 지역균형 뉴딜에서 주요 지자체장이 발표한 정책과 연관하여 살펴보고자 한다.  
author:
  - name: 이광춘
    url: https://www.facebook.com/groups/tidyverse/
    affiliation: 삼정 KPMG
    affiliation_url: https://home.kpmg/kr/ko/home.html
date: "`r Sys.Date()`"
output: 
  distill::distill_article:
    toc: true
    toc_depth: 2
    highlight: tango
    number_section: true
bibliography: bibliography.bib
csl: biomed-central.csl
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# OECD 국가 비교 {#oecd-comparison}


```{r oecd-comparison}
library(tidyverse)
library(reactable)
library(htmltools)
library(countrycode)
library(knitr)

oecd_df <- read_rds("data/oecd_full_df.rds")

oecd_df <- oecd_df %>% 
  select(country, flags, contains("rank"), everything()) %>% 
  mutate(iso2c = countrycode(iso3c, origin = "iso3c", destination = "iso2c") %>% str_to_lower(.)) %>% 
  mutate(gdp = round(gdp/10^9, 0),
         population = round(population / 10^6, 0))
  
oecd_df %>% 
  select(iso2c, country, contains("rank"), everything(), -iso3c, -flags) %>% 
  arrange(ai_rank) %>% 
  reactable(
    filterable = TRUE,
    searchable = TRUE,
    minRows = 10,
    highlight = TRUE,
    columns = list(
        country = colDef(
          html = TRUE,
          cell = JS("function(cell) {
            return '<a href=\"https://wikipedia.org/wiki/' + cell.value + '\">' + cell.value + '</a>'
          }")
        ),
        iso2c = colDef(cell = function(value) {
          img_src <- sprintf('http://flagpedia.net/data/flags/mini/%s.png', value)
          image <- img(src = img_src, height = "24px", alt = "")
          tagList(
            div(style = list(display = "inline-block", width = "45px"), image)
          )
        }),
        gdp = colDef(
          format = colFormat(separators = TRUE)
        ),
        area = colDef(
          format = colFormat(separators = TRUE)
        ),
        gdp_per_capita = colDef(
          format = colFormat(separators = TRUE)
        )
    )
  )
```


# AI 역량 비교 {#oecd-ai-comparison}


```{r ai-capability-comparison}
library(tidymodels)
library(embed)

recipe_spec <- oecd_df %>% 
  na.omit() %>% 
  recipe( ~ .) %>%
    update_role(country, flags, iso2c, iso3c, new_role = "id") %>%
    step_normalize(all_predictors()) %>%
    step_umap(all_numeric(), num_comp = 3, seed = c(123, 123))

umap_tbl <- recipe_spec %>% prep() %>% juice()
# umap_tbl
```

```{r plotly-visualization}
library(plotly)

# 툴팁 데이터 작성
plot_tbl <- umap_tbl %>%
    inner_join(
        oecd_df %>%
            select(country, contains("rank"))
    ) %>%
    mutate(tooltip = str_glue(
        "
        Country: {country}
        WEF Rank: {wef_rank}
        IMD Rank: {digital_rank}
        AI Rank: {ai_rank}
        "
    )) %>% 
  mutate(club_3050 = ifelse(str_detect(country, "United States|Korea|Japan|United Kingdom|France|Germany|Italy"), "30-50 클럽","기타") ) %>% 
  mutate(club_3050 = factor(club_3050, levels = c("30-50 클럽","기타")))
  # mutate(class = case_when(str_detect(country, "United States") ~ "United States",
  #                          str_detect(country, "Korea") ~ "Korea",
  #                          str_detect(country, "Japan") ~ "Japan",
  #                          str_detect(country, "Germany") ~ "Germany",
  #                          TRUE ~ "기타")) %>% 
  # mutate(class = factor(class, levels=c("Korea", "United States", "Japan", "Germany", "기타")))

# Plotly 시각화 ----
plot_tbl %>%
    plot_ly(x = ~ umap_1, y = ~ umap_2, z = ~ umap_3,
            # color = ~ class, colors = c('red', 'blue', 'black', 'pink', 'darkgray'),
            color = ~ club_3050, colors = c('red', 'darkgray'),
            hovertemplate = ~ tooltip) %>%
    add_markers(opacity = 1) %>% 
    add_text(text = ~country, showlegend = FALSE)
```

