CC = xelatex

resume.pdf: resume.tex
	$(CC) $<

cv.pdf: cv.tex
	$(CC) $<

coverletter.pdf: coverletter.tex
	$(CC) $<

clean:
	-rm -f *.aux
	-rm -f *.log
	-rm -f *.toc
	-rm -f *.bbl
	-rm -f *.blg
	-rm -f *.out
	